### PR TITLE
updating iteration variable

### PR DESCRIPTION
**Pull request by emilsavalan**
commiting changes from old repo

### CODE REVIEW

**Comment by jstac** [comment]
Thanks again @emilsavalan .

@mmcky ,  I can't see the netlify link.  Sorry if I'm missing something obvious.

**Comment by mmcky** [comment]
hey @jstac one key limitation of `github actions` is that it won't "naturally" build from forks due to security issues. However there is usually a button to click that says "run github actions after review" that doesn't seem present. I'll check the settings.

**Comment by mmcky** [comment]
I think I see why I will need to update our `ci` configuration. 
Currently it only runs on `push` and it needs to specify `pull_request` to work with fork contributions

https://github.com/quantecon/lecture-python.myst/blob/09b131dad91fa14cd1be2e716257ca5f97890ad7/.github/workflows/ci.yml#L2

I'll try and fix this up later today.

**Comment by mmcky** [comment]
Closing as transferred this to a local branch. Thanks @emilsavalan -- #216

**Pull request closed without merging**
