### PR TITLE
🐛 FIX: Math env syntax issue

### PR DESCRIPTION
**Pull request by AakashGfude**
fixes https://github.com/QuantEcon/lecture-python.myst/issues/102

@mmcky only a few changes needed. rest seems ok.

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @AakashGfude.

I don't see where #70 is reverted. Am I missing something?

**Comment by AakashGfude** [comment]
> I don't see where #70 is reverted. Am I missing something? We should implement those changes in the `rst` repo.

#70 did the same thing as this PR, but with different edits. I think you are right, we should correct the rst sources instead of correcting it here.

**Comment by mmcky** [comment]
oh ok -- so that was reverted on `main` thanks @AakashGfude. Do you mind setting up the PR on lecture-python when you get the chance and I will merge those changes in.

**Comment by mmcky** [comment]
This should not longer be needed with the lastest updates on `main`

**Pull request closed without merging**
