### PR TITLE
MAINT: Upgrade docker to -b (sphinx-reredirects, latest theme)

### PR DESCRIPTION
**Pull request by mmcky**
Maintenance tasks

- [x] update Docker with latest `quantecon-book-theme` and `sphinx-reredirects`

### CODE REVIEW

**Comment by mmcky** [comment]
The following link is no longer valid

````
[pmc.sample](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.sample.html?highlight=sample#pymc.sample) by default uses the NUTS samplers to generate samples as shown in the below cell:

```{code-cell} ipython3
:tag: [hide-output]

with AR1_model:
    trace = pmc.sample(50000, tune=10000, return_inferencedata=True)
```
````

@HumphreyYang do you know if this is getting deprecated in `pymc`?

**Comment by HumphreyYang** [comment]
> The following link is no longer valid
> 
> ```
> [pmc.sample](https://www.pymc.io/projects/docs/en/latest/api/generated/pymc.sample.html?highlight=sample#pymc.sample) by default uses the NUTS samplers to generate samples as shown in the below cell:
> 
> ```{code-cell} ipython3
> :tag: [hide-output]
> 
> with AR1_model:
>     trace = pmc.sample(50000, tune=10000, return_inferencedata=True)
> ```
> ```
> 
> @HumphreyYang do you know if this is getting deprecated in `pymc`?

Many thanks @mmcky, it is indeed deprecated. I will write an issue and update it in a PR

**Comment by mmcky** [comment]
thanks @HumphreyYang -- I will ignore that link issue for now.

**Comment by HumphreyYang** [comment]
> thanks @HumphreyYang -- I will ignore that link issue for now.

We can use https://www.pymc.io/projects/docs/en/v5.10.0/api/generated/pymc.sample.html#pymc-sample for now

**Pull request merged**
