### PR TITLE
ENH: Add link checker GitHub Action

### PR DESCRIPTION
**Pull request by mmcky**
This PR runs a link checker on:

1. schedule (daily),
2. on the creation or reopening of a PR (so only will run once)

### CODE REVIEW

**Comment by mmcky** [comment]
@HumphreyYang do you have time to do the same with this lecture set? Fixing broken for now is ok. 

[linkcheck-reports-2.zip](https://github.com/QuantEcon/lecture-python.myst/files/9502157/linkcheck-reports-2.zip)

**Comment by mmcky** [comment]
@HumphreyYang no rush but when you get a chance to push these can you ping me to review. Thanks.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Thanks for your reminder. There are several issues with the following links:

For these two links, I could not find the `_dowloads` repository under the `https://quantecon.org/lectures/` and it is not in https://github.com/QuantEcon/website/tree/master/_lectures as well.

```
linear_algebra.md:841: [broken] https://lectures.quantecon.org/_downloads/course_notes.pdf: 404 Client Error: Not Found for url: https://quantecon.org/lectures/_downloads/course_notes.pdf

mle.md:138: [broken] https://lectures.quantecon.org/_downloads/mle/fp.dta: 404 Client Error: Not Found for url: https://quantecon.org/lectures/_downloads/mle/fp.dta

```


These two links seem to be working. I think the false positive may be related to the urllib3

```
rational_expectations.md:76: [broken] http://QuantEcon.py: HTTPConnectionPool(host='quantecon.py', port=80): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f64847cd3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
two_auctions.md:654: [redirected permanently] http://faculty.smu.edu/tsalmon/auctions.pdf to https://s2.smu.edu/tsalmon/

ols.md:89: [broken] https://economics.mit.edu/faculty/acemoglu/data/ajr2001: HTTPSConnectionPool(host='economics.mit.edu', port=443): Max retries exceeded with url: /faculty/acemoglu/data/ajr2001 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

```

Could you please help me to resolve these issues? 

Many thanks in advance.

**Comment by mmcky** [comment]
> For these two links, I could not find the _dowloads repository under the https://quantecon.org/lectures/.

@HumphreyYang these files should be now located in `_static/lecture_specific/{lecture-name}`

https://github.com/QuantEcon/lecture-python.myst/tree/main/lectures/_static/lecture_specific/linear_models

**Comment by mmcky** [comment]
@HumphreyYang looks like the `https` requests for these links aren't valid. 

Perhaps we can revert these to http?

https://economics.mit.edu/ -> http://economics.mit.edu/

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I think the linker checking has been passed on this repo. Please kindly review the changes and merge if it looks good to you.

Many thanks.

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Pull request merged**
