### PR TITLE
MAINT: update them to quantecon-book-theme=0.2.1

### PR DESCRIPTION
**Pull request by mmcky**
This updates to use the latest `quantecon-book-theme`

### CODE REVIEW

**Comment by mmcky** [comment]
@shlff this is a build of: https://python-programming.quantecon.org/intro.html using the latest quantecon-book-theme.

@AakashGfude has done some nice work on refactoring our theme and adding some new features.

It would be great if you could spend a bit of time comparing the current live site with this PR build (as a double check).

Hopefully you won't find many differences :-)

**Comment by mmcky** [comment]
@shlff also just to clarify - there is no need to recheck the whole site. Just wanted another set of eyes to:

do some random spot checks
look for some of the issues that have cropped up before

**Comment by mmcky** [comment]
thanks @shlff there are some great pickups here. Thank you!

**Comment by mmcky** [comment]
- [x] bold symbol issue will be added to `mathjax` config (https://github.com/QuantEcon/quantecon-book-theme/issues/120)

**Comment by mmcky** [comment]
@shlff for issue 3 in your list -- I think the actual math is not quite put together as intended. 

```latex
$$
\begin{aligned} p_0  & = x_0 + x_1/R + x_2/(R^2) + \ddots \\
                 & = x_0 (1 + G R^{-1} + G^2 R^{-2} + \cdots ) \\
                 & = x_0 \frac{1}{1 - G R^{-1}} \end{aligned}
$$
```

do you think `\ddots` should be `\cdots`?

**Comment by shlff** [comment]
> @shlff for issue 3 in your list -- I think the actual math is not quite put together as intended.
> 
> ```
> $$
> \begin{aligned} p_0  & = x_0 + x_1/R + x_2/(R^2) + \ddots \\
>                  & = x_0 (1 + G R^{-1} + G^2 R^{-2} + \cdots ) \\
>                  & = x_0 \frac{1}{1 - G R^{-1}} \end{aligned}
> $$
> ```
> 
> do you think `\ddots` should be `\cdots`?

Thanks @mmcky . I think ``\ddots`` is fine, but just notice that the font size of the whole math expression in the preview is larger than that from the live website, which might not be an issue.

**Comment by mmcky** [comment]
- [x] OK `svg` is now enabled via `_config.yml` for `mathjax`

**Comment by mmcky** [comment]
thanks @shlff I think we have addressed the `content` issues that you identified in the lastest update to use `svg` rendering. If you could take a quick look today (~10min) and let me know it is working on your end that would be great.

**Comment by shlff** [comment]
Thanks @mmcky . I just checked them and can confirm that issue 5 mentioned above has been solved.

**Comment by mmcky** [comment]
@AakashGfude @shlff I think we are ready to merge this and deploy `python.quantecon.org` running `quantecon-book-theme=0.2.1`

**Pull request merged**
