### PR TITLE
Migrate Duplicated Lectures

### PR DESCRIPTION
**Pull request by HumphreyYang**
This PR migrates duplicate lectures in https://github.com/QuantEcon/lecture-python-intro/issues/282, `scalar_dynam`, and `complex_and_trig`.

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] wait for https://github.com/QuantEcon/lecture-python-intro/pull/340 to be merged.

**Comment by mmcky** [comment]
@HumphreyYang are you happy for this to be merged? It looks like the requirements are now fulfilled.

**Comment by HumphreyYang** [comment]
Many thanks @mmcky, I think it is ready to be merged.

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Pull request merged**
