### PR TITLE
[harrison_kreps] Fix tables

### LINKED ISSUE #29: [lecture_comparison][harrison_kreps] Markdown Tables are Broken in MyST
Hi @mmcky , I noticed that in lecture [harrison_kreps](https://quantecon.github.io/lecture-python.myst/harrison_kreps.html),
- all tables written using ``markdown`` are broken (left: ``MYST``, right: ``RST``)

For example, please see the following:
Screen Shot 2021-01-04 at 1 03 22 pm

And also in this lecture,
Screen Shot 2021-01-06 at 4 02 40 pm

### PR DESCRIPTION
**Pull request by mmcky**
fixes #29 

This PR manually fixes the tables in `harrison_kreps` lecture due to https://github.com/executablebooks/sphinx-tomyst/issues/90

### CODE REVIEW

**Comment by mmcky** [comment]
I have added an issue on [quantecon-book-theme] for styling of tables

https://github.com/QuantEcon/quantecon-book-theme/issues/79

**Review by shlff — COMMENTED** [review]
Thanks @mmcky . Nice work! 

The first broken table in lecture [harrison_kreps](https://quantecon.github.io/lecture-python.myst/harrison_kreps.html) has been fixed (left: the preview of this PR, right: original ``MYST``):
Screen Shot 2021-01-06 at 3 21 33 pm

Its second broken table (in Exercise 1) has not been fixed yet:
Screen Shot 2021-01-06 at 3 22 10 pm

Should we fix the 2nd one in this or another PR?

**Comment by mmcky** [comment]
Thanks @shlff not yet -- let's hold off on these manual type changes until we freeze `lecture-python` for edits as the source.

**Comment by mmcky** [comment]
> Its second broken table (in Exercise 1) has not been fixed yet:

@shlff would you mind fixing the second table and committing to this branch?

**Comment by shlff** [comment]
Thanks @mmcky . As you can see from the screenshot of the above lecture preview, the second table has been fixed as well.

Screen Shot 2021-03-02 at 2 40 07 pm

**Comment by mmcky** [comment]
great - thanks @shlff

**Comment by mmcky** [comment]
thanks @shlff

**Comment by mmcky** [comment]
thanks @shlff. Also it is good **not** to use force push if you don't have to. So make sure you have `git pull` on a branch to get the latest.

**Pull request merged**
