### PR TITLE
PCA section in SVD lecture

### PR DESCRIPTION
**Pull request by sidd3888**
Made the changes referenced in issue #396.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Many thanks @sidd3888 for contributing! We will get this merged very soon once we get green ticks.

**Comment by mmcky** [comment]
thanks for reviewing @HumphreyYang -- greatly appreciated. 

thanks @sidd3888 for the PR. 

@HumphreyYang would you mind to review the merge conflict?

**Comment by mmcky** [comment]
thanks @HumphreyYang. This OK to merge now?

**Comment by mmcky** [comment]
thanks again @sidd3888 and @HumphreyYang

**Pull request merged**
