### PR TITLE
Modify the callings of LinearStateSpace.stationary_distributions

### PR DESCRIPTION
**Pull request by mmcky**
Modify the code in the lectures related with the recent change in QuantEcon/QuantEcon.py#569

Thanks @shizejin I have migrate this from the `RST` repository. 

If you could review and approve this PR that would be great. 

- [x] setup a new release of `QuantEcon.py` and check this runs before merging

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] configure `jupyter-book` to report failure due to execution failures

**Review by shizejin — APPROVED** [review]

**Comment by mmcky** [comment]
OK so not sure why but this isn't working on the planned new release for `quantecon`

https://github.com/QuantEcon/QuantEcon.py/pull/578

I will need to look into this further.

**Comment by mmcky** [comment]
OK so I think this is failing as the `quantecon` installs within the lectures are fetching from `pip` so I will:

- [ ] set a version pin on the environment for the lecture build and remove it once this PR is building on the new release

**Comment by mmcky** [comment]
@shizejin I have just issued a new release of `QuantEcon.py` via `pip`. It usually takes a couple of days to feed into `conda` so I will rerun this CI once `quantecon=0.5.0` is available via `conda`.

**Comment by mmcky** [comment]
- [ ] waiting for `quantecon=0.5.0` to be in `pkgs/main` for `anaconda`

The update is now avaialble via `conda-forge` so we could update to use `-c conda-forge` but should be a day or two for `pkgs/main`

**Comment by mmcky** [comment]
thanks @shizejin the updated QuantEcon.py packages is now in `pkgs/main` for `anaconda`

**Pull request merged**
