### PR TITLE
FIX: Adjust for quantecon==0.6.0

### PR DESCRIPTION
**Pull request by mmcky**
Migrates #286 to be local (cc: @Smit-create)

### CODE REVIEW

**Comment by mmcky** [comment]
@Smit-create 

I am getting this warning

```
/tmp/ipykernel_8015/2878916857.py:2: UserWarning: The API of tauchen has changed from `tauchen(rho, sigma_u, b=0., m=3, n=7)` to `tauchen(n, rho, sigma, mu=0., n_std=3)`. To find more details please visit: https://github.com/QuantEcon/QuantEcon.py/issues/663.
  mc = qe.tauchen(n, 0.96, 0.25)
```

in the preview of `markov_asset`

Do we need to run through an update the imports so these warnings are not presented?

**Comment by mmcky** [comment]
I have tagged this as `high-priority` as `quantecon==0.6.0` is now available on `PyPI`

**Comment by Smit-create** [comment]
> 

These warnings are expected. This warns users about this breaking change. It would be good to have atleast for sometime.

**Comment by mmcky** [comment]
> These warnings are expected. This warns users about this breaking change. It would be good to have atleast for sometime.

I was expecting them to show up when the old format was used (rather than the new format). I think if a user is using what the new `api` will be there shouldn't be a warning issued right?

**Comment by mmcky** [comment]
> > These warnings are expected. This warns users about this breaking change. It would be good to have atleast for sometime.
> 
> I was expecting them to show up when the old format was used (rather than the new format). I think if a user is using what the new `api` will be there shouldn't be a warning issued right?

@Smit-create is this warning showing up due to the import structure. If we update the imports to the new location will that remove this warning? Or will it show up whenever this function is used?

**Comment by Smit-create** [comment]
> is this warning showing up due to the import structure.

No, this is because of changes in `tauchen`.

> Or will it show up whenever this function is used?

Yes, that's right. Can we keep these warnings for one version and remove them in the upcoming versions? This reason is that there is not much clear difference between the old and new APIs such that we can throw warnings only to users of the old API.

**Comment by Smit-create** [comment]
Or else if we strictly want this warning to show only when the user uses the old API, one minor difference which I noticed is that:
Previously, the first argument of `tauchen` was float and now it should be an integer. We can throw this warning whenever we encounter a float at the first argument but this is still a bit hackish.

**Comment by mmcky** [comment]
> Or else if we strictly want this warning to show only when the user uses the old API, one minor difference which I noticed is that:
> Previously, the first argument of `tauchen` was float and now it should be an integer. We can throw this warning whenever we encounter a float at the first argument but this is still a bit hackish.

Roger that - changes in positional arguments are hard to track at the function level and we haven't changed the name of the function so hard to identify. We could use the function signature (based on types) to identify old usage patterns though. I don't think that's a bad idea as it is confusing to get a warning when you have updated the order.

**Comment by mmcky** [comment]
thanks for the updates @Smit-create I am going to merge this PR now so the cache will run using the latest quantecon release.

**Pull request merged**
