### PR TITLE
MAINT: update the software stack

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates

- [x] anaconda
- [x] jupyter-book
- [x] quantecon-book-theme
- [x] sphinx-exercise
- [x] sphinx-tojupyter

### CODE REVIEW

**Comment by mmcky** [comment]
- [ ] check `arg\\max` and `arg\\min` rendering in math

**Comment by mmcky** [comment]
hey @shlff can you let me know if you're planning to review this PR? No worries if you don't have the time. I'll set some time aside next week to review so it can be merged.

**Comment by shlff** [comment]
Thanks for reminding me of this @mmcky . Actually I reviewed this PR last month but I forgot to update my reports here. I would take time to recall the issues I find and report them to you by next Monday (22nd Nov.).

**Comment by mmcky** [comment]
@shlff I just updated `anaconda` to the `2021.11` from `2021.05` (which was causing some issues). Hopefully the `2021.11` will be more stable. Looks god so far from my review.

**Comment by mmcky** [comment]
From my review this morning I think this is looking pretty complete.

**Comment by mmcky** [comment]
@shlff I am going to merge this so if there are any `bugs` that you come across let me know and we can issue a fix.

**Comment by shlff** [comment]
Thanks @mmcky . I quickly went through the  ``HTML`` and ``download pdf`` of the lectures quickly and didn't find any big issues. They look good to me. 

I have been reading the ``HTML`` and ``ipynb`` files of the lectures one by one carefully and I will report in the issue tracker if I spotted any issue.

**Comment by mmcky** [comment]
thanks for the update @shlff that gives me confidence :-).

**Pull request merged**
