### PR TITLE
Update jax box at top of lecture, update CUDA to 11.8

### LINKED ISSUE #317: [jax] Very slow compilation time in wealth_dynamics
The cache is reporting a very slow compilation time for one of our `jax` requests on [190](https://github.com/QuantEcon/lecture-python.myst/actions/runs/4238029946/jobs/7364713704#step:7:190)

```bash
Executing: /__w/lecture-python.myst/lecture-python.myst/lectures/wealth_dynamics.md
external/org_tensorflow/tensorflow/compiler/xla/service/slow_operation_alarm.cc:65] 
********************************
[Compiling module jit_wealth_time_series_for_loop_jax] Very slow compile?  If you want to file a bug, run with envvar XLA_FLAGS=--xla_dump_to=/tmp/foo and attach the results.
```

### PR DESCRIPTION
**Pull request by Smit-create**
Fixes #317

### CODE REVIEW

**Comment by Smit-create** [comment]
Now we have this error:
```
2023-02-24 04:15:25.073842: E external/org_tensorflow/tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:429] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-02-24 04:15:25.075158: E external/org_tensorflow/tensorflow/compiler/xla/status_macros.cc:57] INTERNAL: RET_CHECK failure (external/org_tensorflow/tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:627) dnn != nullptr
```

I got the same error earlier on Colab which was fixed by this: https://github.com/google/jax/issues/14464#issuecomment-1429759887.

**Comment by HumphreyYang** [comment]
Many thanks @Smit-create,

I think new errors may be due to incompatible versions: https://github.com/google/jax/issues/14480. I will try to get another version of `jaxlib` to give it a go.

**Comment by Smit-create** [comment]
We are having cuda-11.4 so we should go with this:
```
pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
```
and, I think we also need to change this in ci.yml to be used in our environment.

**Comment by HumphreyYang** [comment]
> We are having cuda-11.4 so we should go with this:
> 
> ```
> pip install "jax[cuda11_cudnn82]" -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
> ```
> 
> and, I think we also need to change this in ci.yml to be used in our environment.

Many thanks @Smit-create, I tried this in https://github.com/QuantEcon/lecture-python.myst/actions/runs/4259940753/jobs/7412653081, but the error still comes out. I am looking into `cudnn` version now.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

I suspect that this error is related to the version of `cudnn`. Could you please give us extra information about `cudnn` version on the server?

Many thanks in advance.

**Comment by mmcky** [comment]
The error still persists with lots of different combinations of `cuda` 

```
Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
```

Doing some searching suggests memory issues? I am all hears if anyone has any leads.

**Comment by HumphreyYang** [comment]
> The error still persists with lots of different combinations of `cuda`
> 
> ```
> Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
> ```
> 
> Doing some searching suggests memory issues? I am all hears if anyone has any leads.

Hi @mmcky,

My guess is that this may be an issue with `cudnn`. I saw this error before when there is an incompatible `cudnn`, and https://github.com/google/jax/issues/989 suggests that this may be an environment path or symlink issue.

**Comment by mmcky** [comment]
@Smit-create @HumphreyYang it looks like the magical incantation is:

```
jax[gpu] == 4.2.0
cuda==11.8
```

This `cuda` is the newest version available via `nvidia/docker` so it should work for a while 🤞

**Comment by HumphreyYang** [comment]
> @Smit-create @HumphreyYang it looks like the magical incantation is:
> 
> ```
> jax[gpu] == 4.2.0
> cuda==11.8
> ```
> 
> This `cuda` is the newest version available via `nvidia/docker` so it should work for a while 🤞

Many thanks @mmcky. That's great news!

**Comment by Smit-create** [comment]
Thanks, @mmcky. I'm glad to see this working again!

**Pull request merged**
