### PR TITLE
AR1 Bayes Fixes

### LINKED ISSUE #252: AR1 Bayes lecture comments
@thomassargent30 @smit-create, I really enjoyed reading the lecture https://python.quantecon.org/ar1_bayes.html

Some minor suggestions:

It is not clear from reading the lecture why we are using both pymc and numpyro.   Is it because they give different insights or because we want to show how to use both libraries?  Some guidance for the reader would be helpful.

It would help the reader if there was a bit more guidance about the numpyro implementation.  E.g., what is NUTS?  Just one or two lines, and perhaps a few links?

Add "the" to "The first component of statistical model"

### PR DESCRIPTION
**Pull request by Smit-create**
#252 

cc @jstac @thomassargent30

### CODE REVIEW

**Comment by Smit-create** [comment]
I will add further commits to address the comments:
1. Why do we use both `pymc` and `numpyro`?
2. Some explanation of `numpyro`.

**Comment by jstac** [comment]
Many thanks @Smit-create .  I will leave it to you and @thomassargent30 to finalize these changes.

**Comment by Smit-create** [comment]
@thomassargent30 I have added some comments on NUTS. Please review the changes and let me know if you have any suggestions. @mmcky Can you please approve the workflow so that we can check the deployment? Thanks!!

**Comment by mmcky** [comment]
hey @Smit-create I have added you as a member for the QuantEcon organisation of GitHub. Maybe that will fix these permissions for running checks etc. Once you accept -- hopefully they will run for you.

**Comment by Smit-create** [comment]
> Maybe that will fix these permissions for running checks etc. Once you accept -- hopefully they will run for you.

Thank you so much! It works.

**Pull request merged**
