### PR TITLE
[mccall_model] Transfer #195: Updating Iteration Variable

### PR DESCRIPTION
**Pull request by mmcky**
This is a local version of #195

### CODE REVIEW

**Comment by mmcky** [comment]
@jstac this looks good to go now.

**Comment by mmcky** [comment]
@HumphreyYang can you review this stale PR and confirm that it is still relevant. Thanks.

**Comment by HumphreyYang** [comment]
> @HumphreyYang can you review this stale PR and confirm that it is still relevant. Thanks.

Many thanks @mmcky, this is still relevant and is a good improvement to the coding style.

**Comment by mmcky** [comment]
Thanks @HumphreyYang

**Comment by mmcky** [comment]
thanks @emilsavalan for this contribution. Sorry it has taken so long to merge. It is greatly appreciated.

**Pull request merged**
