### PR TITLE
Fix typos and latex errors in prob_matrix.md

### PR DESCRIPTION
**Pull request by natashawatkins**
* I also changed Jupiter notebook settings to only show up to the 3 decimal places

### CODE REVIEW

**Comment by jstac** [comment]
Thanks @natashawatkins !

When I look in "Files changed" I see only a small change to one file.  Is anything missing?

**Comment by natashawatkins** [comment]
@jstac those were all the typos I found. I was trying to change the decimal place display option in Jupyter but that caused the tests to fail, so maybe I will leave that...

**Comment by mmcky** [comment]
thanks @natashawatkins.

@jstac I am seeing 20 lines have changed. Tom has also reviewed these changes and approves (let me know via email). so I will go ahead and merge this soon. 

@natashawatkins Tom asked if you would mind have a look over the Samuelson lecture and "check the killer graph" you put together for that lectures :-).

**Comment by jstac** [comment]
@natashawatkins @mmcky weird, I'm now seeing all the changes too.

@natashawatkins Thanks heaps, much appreciated!

**Comment by natashawatkins** [comment]
@mmcky was there anything specific about the plot? I can see some of the legends have gotten a little wonky..

**Pull request merged**
