### PR TITLE
MAIN: Update tauchen API according to new change in PR-664 (Quantecon.py)

### PR DESCRIPTION
**Pull request by Smit-create**

### CODE REVIEW

**Comment by Smit-create** [comment]
This PR depends on https://github.com/QuantEcon/QuantEcon.py/pull/664.

**Comment by mmcky** [comment]
thanks @Smit-create can we set this up as a local branch (or add the adjustments to #286) and I will rename that PR. To get access to GitHub secrets requires local branch for running the test builds.

**Comment by mmcky** [comment]
From #286 the only lecture failing on the new `quantecon` main is `markov_asset` so I will leave this PR open and close the testing PR.

**Comment by mmcky** [comment]
@Smit-create this isn't running due to being in a fork. Can you migrate these to a local branch if you have time -- otherwise I will do so later this afternoon. Thanks.

**Pull request closed without merging**
