### PR TITLE
Revert JAX Content in Newton's Method 

### LINKED ISSUE #339: Remove JAX material from Newton lecture
Regarding https://python.quantecon.org/newton_method.html

Summary: this lecture contains JAX material that is now redundant, since we cover the same material in the JAX lecture series.

TODO

- Remove everything from "A High-Dimensional..."
- In two good case, first do manual Newton via the derivatives calculated by hand in https://python.quantecon.org/newton_method.html#adding-gradient-information
- Then use a SciPy root finder, discuss the difference
- Remove JAX imports

### PR DESCRIPTION
**Pull request by HumphreyYang**
This resolves #339.

### CODE REVIEW

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Could you please send me the error log, as the error did not appear in my local build?

Many thanks in advance.

**Comment by mmcky** [comment]
@HumphreyYang if you: 

1. click on the failed build link
2. click on `Summary`

you can download the execution error reports as a build artifact.

**Comment by mmcky** [comment]
In this case the error is

```
ValueError: shapes (3,3) and (3000,) not aligned: 3 (dim 1) != 3000 (dim 0)
```

**Comment by HumphreyYang** [comment]
Many thanks @mmcky,

This is strange. I just couldn't replicate the error locally and the error is not related to the environment. Would you mind resetting the cache so that I can have another go?

**Comment by mmcky** [comment]
@HumphreyYang is this expected behaviour for `iteration == 1`

Screenshot 2023-05-10 at 12 56 47 pm

**Comment by HumphreyYang** [comment]
> @HumphreyYang is this expected behaviour for `iteration == 1`
> 
> 
> 
> Screenshot 2023-05-10 at 12 56 47 pm
> 
> 

Many thanks @mmcky, 

This is expected as it shows sometimes newton's method can fail.

**Comment by HumphreyYang** [comment]
Hi @mmcky,

The errors now are:

```
/__w/lecture-python.myst/lecture-python.myst/lectures/mccall_model.md:687: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
/__w/lecture-python.myst/lecture-python.myst/lectures/career.md:470: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
```

**Comment by mmcky** [comment]
> Hi @mmcky,
> 
> The errors now are:
> 
> ```
> /__w/lecture-python.myst/lecture-python.myst/lectures/mccall_model.md:687: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
> /__w/lecture-python.myst/lecture-python.myst/lectures/career.md:470: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
> ```
> 
> Any ideas on how should I resolve them?
> 
> Many thanks in advance.

Those errors mean there is some traceback in some output. Can you replicate this locally on a clean build?

**Comment by mmcky** [comment]
I am getting them locally on `quantecon-gpu-server1`

```
/home/mmcky/work/lecture-python.myst/lectures/career.md:470: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
/home/mmcky/work/lecture-python.myst/lectures/mccall_model.md:735: WARNING: Could not lex literal_block as "ipythontb". Highlighting skipped.
```

and it looks like `no python jit` is failing

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function draw at 0x7f5cca47b400>) found for signature:
 
 >>> draw(array(float64, 1d, C))
```

**Comment by mmcky** [comment]
@HumphreyYang I will open a separate to test build the current main to rule that out.

**Comment by mmcky** [comment]
- [ ] @mmcky to review `pdf`

**Comment by HumphreyYang** [comment]
Hi @jstac,

This is now ready for your review. As this PR resolves some of the bugs that appeared in the CI, once this is merged, I will do a merge in each PR to get the CI building again.

Many thanks.

**Comment by mmcky** [comment]
@HumphreyYang the issue with the `pdf` should be fixed by #343

**Comment by HumphreyYang** [comment]
> @HumphreyYang the issue with the `pdf` should be fixed by #343

Many thanks @mmcky. I saw the PDF has been built successfully. Please merge the PR when you are ready and I will merge main to this and hand it over to @jstac!

**Comment by mmcky** [comment]
> > @HumphreyYang the issue with the `pdf` should be fixed by #343
> 
> Many thanks @mmcky. I saw the PDF has been built successfully. Please merge the PR when you are ready and I will merge main to this and hand it over to @jstac!

@HumphreyYang I merged `main` in so should be fixed after this build.

**Comment by HumphreyYang** [comment]
Hi @jstac,

This PR is ready for your review.  Many thanks in advance.

**Comment by HumphreyYang** [comment]
Hi @jstac,

This PR is ready for your review. Many thanks in advance.

**Comment by HumphreyYang** [comment]
As the bug in `quantecon.py` has been fixed. I will revert the temprary fix in this PR.

**Comment by jstac** [comment]
Many thanks @HumphreyYang .

@mmcky , would you mind to keep handling this one?

**Comment by mmcky** [comment]
- [ ] needs a new release of `quantecon==0.7.1`

**Comment by HumphreyYang** [comment]
Hi @mmcky,

This is ready to be merged. Please kindly review these changes and let me know if further changes are needed.

Many thanks.

**Comment by mmcky** [comment]
thanks @HumphreyYang

**Comment by HumphreyYang** [comment]
Hi @mmcky,

Should we wait for the build to come alive before we publish? I will have a quick look to see what changes were brought into the lecture.

Many thanks.

**Comment by mmcky** [comment]
@HumphreyYang I will wait until we get green ticks on the fresh cache build before triggering a publish. That currently takes 1.5 hours so I will release the update later this evening.

**Comment by mmcky** [comment]
@HumphreyYang please check the final build on this PR and let me know if all looks as expected. I merged to get the `cache` building

**Comment by HumphreyYang** [comment]
Hi @mmcky, looks like the merge got some JAX into the lecture. I will restore this branch and merge it again. Apologies for the inconvenience.

**Pull request merged**
