### PR TITLE
Update lecture-python sources with latest updates

### PR DESCRIPTION
**Pull request by mmcky**
This PR updates the source files from lecture-python (dbd838d) using sphinx-tomyst (b06cacb)

@shlff this PR should contain all of your recent PR's that have been merged in addition to changes from Tom and John (over the past two weeks). 

If you could take a look to see it looks as expected (from your commits) that would be great.

### CODE REVIEW

**Comment by mmcky** [comment]
**Note:** this will be missing the 6 lectures that require code execution until #16 is merged.

**Comment by mmcky** [comment]
@shlff I am going to merge this now but when you get the chance I'd appreciate you taking a quick look at the `diff` and let me know if it looks about right -- with regards to your recent changes. I have converted this from `lecture-python` using `sphinx-tomyst`

**Comment by shlff** [comment]
Great thanks for your nice work, @mmcky . Sorry for my late reply. ``sphinx-tomyst`` is really cool!

I checked all this PR's changes, most of which look right except the one for lecture ``short_path.md``:

Screen Shot 2021-01-06 at 10 59 23 pm

Since it is in ``myst``, so the context after the change in that lecture (the left in the above screenshot) should be:
- ``(Graphs such as the one above are called **weighted [directed graphs](https://en.wikipedia.org/wiki/Directed_graph)**.)``

Do you want me to submit a PR to correct this?

I will check these more carefully again, compared with my merged PRs in ``lecture-python``.

**Comment by mmcky** [comment]
@shlff looking at the source `rst` this seems correct

```rst
(Graphs such as the one above are called **weighted `directed graphs <https://en.wikipedia.org/wiki/Directed_graph>`_**.)
```

**Comment by mmcky** [comment]
@shlff oh I see the issue -- thanks. It should be updated. Would you mind setting up a new PR in this repo with the update and tag it as `manual-change`

**Pull request merged**
