### PR TITLE
FIX: solve_model methods (fixing)

### PR DESCRIPTION
**Pull request by shlff**
Thanks for @oyamad and @kuramogura's notification. 

Hi @jstac @oyamad and @mmcky , this PR corrects the pattern in [files](https://github.com/QuantEcon/lecture-python.myst/search?q=%22if+verbose+and+i+%3C+max_iter%22) mentioned by @oyamad with the following (fixing, please do not merge it)
```
if i == max_iter and error > tol:
      print("Failed to converge!")
elif verbose:
      print(f"\nConverged in {i} iterations.")  
```

### CODE REVIEW

**Comment by mmcky** [comment]
@shlff just updated this PR from the `main` branch

**Comment by mmcky** [comment]
@shlff can you investigate this issue

```
WARNING: Execution Failed: /home/runner/work/lecture-python.myst/lecture-python.myst/lectures/odu.md
```

**Comment by mmcky** [comment]
@shlff do you have time to review this?

**Comment by shlff** [comment]
Thanks @mmcky . I will check this PR and get back to you by today.

**Pull request closed without merging**
