### PR TITLE
MAINT: Fix small typos

### PR DESCRIPTION
**Pull request by Smit-create**
This PR

- removes `%matplotlib inline` as no longer required
- removes redundant white space
- removes `+++` markers introduced by `jupytext` conversion

cc @mmcky

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @Smit-create this looks great. Would you mind to resolve the minor conflicts and then I will merge.

**Comment by mmcky** [comment]
> thanks @Smit-create this looks great. Would you mind to resolve the minor conflicts and then I will merge.

@ kp992 would you mind to look into this?

**Comment by kp992** [comment]
Thanks @mmcky. I have rebased it and made the changes locally but seems like a permission issue to push it on this branch.
```
remote: Permission to QuantEcon/lecture-python.myst.git denied to kp992.
fatal: unable to access 'https://github.com/QuantEcon/lecture-python.myst.git/': The requested URL returned error: 403
```

**Comment by mmcky** [comment]
thanks @kp992 you are now a member of the `python-lectures` team

**Comment by kp992** [comment]
> thanks @kp992 you are now a member of the `python-lectures` team

thanks @mmcky. It's still showing the same error.

**Comment by mmcky** [comment]
> > thanks @kp992 you are now a member of the `python-lectures` team
> 
> thanks @mmcky. It's still showing the same error.

@kp992 I believe you will need to fix the merge conflicts before the `ci` will run again

**Comment by kp992** [comment]
I have merged the main branch into this branch, but when I try to push, I get the above error.

**Comment by mmcky** [comment]
Oh I see -- try now?

**Comment by kp992** [comment]
Done @mmcky, thank you so much.

**Comment by mmcky** [comment]
thanks @Smit-create I will do a final review and merge once #361 and #355 are finalised

**Review by mmcky — APPROVED** [review]
thanks for this tidy up @Smit-create

**Comment by mmcky** [comment]
@Smit-create I am just running a full run without the build cache to test execution given there are some imports removed.

**Comment by Smit-create** [comment]
Seems like everything is looking good. Thanks @mmcky

**Review by mmcky — APPROVED** [review]
thanks @Smit-create -- this is great. 

Please remember to fill in the top comment box with a description of the changes. I have added this to this PR. Thank you.

**Pull request merged**
