### PR TITLE
ENH: Upgrade docker with anaconda==2023.03

### PR DESCRIPTION
**Pull request by mmcky**
- [x] check `jax` and `gpu` computing
- [x] check compatibility with `anaconda==2023.03`

### CODE REVIEW

**Comment by mmcky** [comment]
- updated `3d` projections to

```
ax = plt.figure(figsize = (10, 6)).add_subplot(projection='3d')
```

**Comment by mmcky** [comment]
@jstac @HumphreyYang this is now showing as running on the `gpu` after installing `jax == 0.4.8` in the docker container and connecting it to the latest `cuda 12.1` release

**Comment by mmcky** [comment]
@HumphreyYang @Smit-create if you have any time can you please take a look through the preview deployment above and let me know if you see any issues. This PR is moving to:

1. `anaconda==2023.03` which is the latest set of packages
2. `jax[cuda12_pip]`
3. `cuda 12.1` docker container from Nvidia

I noticed that the drivers being reported by `nvidia-smi` are `470.161.03` which appears to be an issue for `cuda 12` so I don't quite understand but the lectures are reporting `gpu` backend. 

I am doing some research into how to update the drivers on `aws` instances `p3.2xlarge`

**Comment by Smit-create** [comment]
Thanks @mmcky, The execution of Wealth Dynamics looks fine to me. The results are errorless and as expected, JAX is faster than numba.

**Comment by mmcky** [comment]
thanks @Smit-create and @HumphreyYang

**Pull request merged**
