### PR TITLE
[22_cass_koopmans_2] Fix SyntaxWarning

### LINKED ISSUE #62: [downloadnb-comparison] [21_cass_koopmans_2] SyntaxWarning
Hi @mmcky , I find the following ``SyntaxWarning`` in lecture [21_cass_koopmans_2](https://quantecon.github.io/lecture-python.myst/cass_koopmans_2.html) (left: ``RST``, right: ``MYST``):

Screen Shot 2021-01-27 at 4 48 35 pm

Screen Shot 2021-01-27 at 4 51 08 pm

This issue can be fixed by changing ``is`` to ``==``.

Do you think it is a good idea for me to create a PR to fix it in ``RST`` repo?

### PR DESCRIPTION
**Pull request by shlff**
Hi @mmcky , this PR fix #62 by 
- changing ``is`` to ``==`` in lecture [cass_koopmans_2](https://quantecon.github.io/lecture-python.myst/cass_koopmans_2.html)

### CODE REVIEW

**Comment by mmcky** [comment]
thanks @shlff is there any reason we can't make this change in the `rst` repo?

**Comment by sayaikegawa** [comment]
Thanks @shlff , the next code-block in [this section](https://601a46da7b65c0a11b7464c4--nostalgic-wright-5fa355.netlify.app/cass_koopmans_2.html#varying-curvature) also has the same problem. (in line 874 and 876).

fix #46

**Comment by shlff** [comment]
Thanks @mmcky and @sayaikegawa , I will make the change here and that mentioned by Saya in the ``rst`` repo very soon.

**Comment by mmcky** [comment]
thanks @shlff once you have migrated the change -- please close this PR when you're ready.

**Comment by shlff** [comment]
Thanks @mmcky . I migrated this PR and will close it.

**Pull request closed without merging**
