### PR TITLE
Fix small typos in McCall Q learning

### PR DESCRIPTION
**Pull request by jstac**

### CODE REVIEW

**Comment by jstac** [comment]
There are some hard-coded equation numbers that need to be fixed --- for example, 

- "described in equation system (4) lets"
- "with our Q-learning recursion (3)"
- "Q-table defined in equation (2) automatically "

**Comment by jstac** [comment]
Hi @mmcky , what do you think is happening here (link checker fail)?

**Comment by HumphreyYang** [comment]
Hi @jstac, 

I saw my link checker passed, so I rerun the link checker in your PR. I think the server of that website was overloaded, but it is now passing.

**Comment by mmcky** [comment]
@mmcky sometimes the link checker fails if a server takes too long to respond. It's annoying part hard to fix. Most of the time it returns a reliable result. FWIW the link checker only runs on the first PR creation so if there are any edits it won't block the PR.

**Comment by mmcky** [comment]
thanks @shlff did you address all 3 equation reference updates?

**Comment by jstac** [comment]
Many thanks @shlff .  Merging.

**Pull request merged**
